### ISSUE TITLE
when i use the UVAtlasCreate() function,and I pass std::vector vects and indexs,get the error 80004005

### ISSUE THREAD

**Issue by yangshuang-developer** [Microsoft/UVAtlas#11]
output:
verts 375,nFaces:146
Computing isochart atlas on mesh ...
0.00%
Error:Failed creating isocharts(80004005)

I don't know what mistake I had made,can you give me some advises?

**Comment by walbourn** [comment]
0x80004005 is a fairly generic error ``E_FAIL``. Can you step into the code to see where it returns this error?

Have you looked at the source code in [UVAtlas tool](https://github.com/Microsoft/UVAtlas/blob/master/UVAtlasTool/UVAtlas.cpp)?

**Comment by yangshuang-developer** [comment]
yes,as the wiki say,UVAtlasCreate performs the same operation as UVAtlasPartition then UVAtlasPack.The first Partition is success,but the second pack is error.did I pass some wrong arguments into the API?

**Comment by yangshuang-developer** [comment]
I have looked at the source code in UVAtlas tool,but I don't find the error description,only the E_FAIL return.
