### ISSUE TITLE
Can I use UVAtlas code in commercial application?

### ISSUE THREAD

**Issue by PolarNick239** [Microsoft/UVAtlas#12]
Thanks for this project, and big thanks for MIT license, but isn't UVAtlas usage constrained by patent [US7224356](https://www.google.com/patents/US7224356)? Doesn't that patent makes impossible production usage of UVAtlas?

**Comment by walbourn** [comment]
The original MS-PL license addressed patents, but the preferred MIT license does not. I'll work with our legal team  to see if I can get a patents statement to attach to clarify any concerns here.

**Comment by PolarNick239** [comment]
Thanks, I found MS-PL revision and that's great.
Maybe you have some rough ETA for clarification?

**Comment by PolarNick239** [comment]
Sorry for impatience, but I think that it can help - Apache License 2.0 seems to address patents while seems to be similar to MIT. May be this is exactly what is needed?

**Comment by walbourn** [comment]
I've contacted our legal department to get some official guideance on this issue... Thank you for your continued patience.

**Comment by exavi** [comment]
I'm very interested in this as well, did the legal department ever get back to you?

**Comment by walbourn** [comment]
Alas, after may months our legal department declined to provide anything official beyond the terms of the generic MIT license. They only said that if someone has any concerns, they should seek their own legal counsel.

I will refrain from any personal commentary on this position lest it be misunderstood as an official statement. I can say that there are commercial products using UVAtlas, and that the primary motivation for open sourcing UVAtlas in the first place was to allow commercial products to remove their dependacy on the deprecated ``D3DX9`` library.

Sorry for not being able to provide anything else more helpful in this regard.

**Comment by breakin** [comment]
For reference there is also patent https://patents.google.com/patent/US7425954B2/en
