### ISSUE TITLE
How can I export the mesh data into OBJ file？

### ISSUE THREAD

**Issue by vely915** [microsoft/UVAtlas#13]

**Comment by walbourn** [comment]
I don't currently support writing to an Wavefront ``obj`` file since the format is so simple, only as an input. I can certainly consider this a feature request for the ``uvatlas`` tool as well as the DirectXMesh ``meshconvert`` which uses the same helper ``Mesh`` class.

**Comment by WurmD** [comment]
Here is code to export to an OBJ if added to WaveFrontReader.h

	class ThreeFloatAndIndex
	{
	public:
		float x;
		float y;
		float z;
		size_t index;

		ThreeFloatAndIndex(float oX, float oY, float oZ, size_t oIndex) : x(oX), y(oY), z(oZ), index(oIndex) {}

		bool operator< (const ThreeFloatAndIndex& rhs) const
		{
			if (this->x < rhs.x)
				return true;
			if (this->x == rhs.x && this->y < rhs.y)
				return true;
			if (this->x == rhs.x && this->y == rhs.y && this->z < rhs.z)
				return true;
			return false;
		}
	};


	template<class index_t>
	class WaveFrontReader
	{
	public:

		/// Write to file
		void ToOBJ(std::string filePath) const
		{
			std::ofstream os;
			os.open(filePath);
			ToOBJ(os);
		}
		/// Writing to cout or to a file stream
		void ToOBJ(std::ostream& os) const
		{
			os << "mtllib ./" << std::string(name.begin(), name.end()) << ".mtl" << std::endl; // https://stackoverflow.com/questions/4804298/how-to-convert-wstring-into-string
			// converting wstring to string this way works for almost everything except chinese characters	

			// Collect all "v", vn, and vt into a unique sets (bc there may be repetitions in the triples above)
			// Note: faster than adding to a set may be adding to a vector and then sort unique it, needs testing
			//		 ie., sort( vec.begin(), vec.end() ); vec.erase(unique(vec.begin(), vec.end()), vec.end());

			std::set<ThreeFloatAndIndex> vsTemp;
			std::set<ThreeFloatAndIndex> vtsTemp;
			std::set<ThreeFloatAndIndex> vnsTemp;
			for (auto vertex : vertices)
			{
				vsTemp.emplace(vertex.position.x, vertex.position.y, vertex.position.z, 0);
				if (hasTexcoords)
					vtsTemp.emplace(vertex.textureCoordinate.x, vertex.textureCoordinate.y, 0, 0);
				if (hasNormals)
					vnsTemp.emplace(vertex.normal.x, vertex.normal.y, vertex.normal.z, 0);
			}

			// Print the v's, vt's and vn's to output, and store their indexes (to later use in the f's)
			std::set<ThreeFloatAndIndex> vs;
			std::set<ThreeFloatAndIndex> vts;
			std::set<ThreeFloatAndIndex> vns;

			size_t index = 1;
			for (auto v : vsTemp)
			{
				os << "v " << v.x << " " << v.y << " " << v.z << std::endl;
				vs.emplace(v.x, v.y, v.z, index);
				index++;
			}
			
			if (hasTexcoords)
			{
				index = 1;
				for (auto vt : vtsTemp)
				{				
					os << "vt " << vt.x << " " << vt.y << std::endl;
					vts.emplace(vt.x, vt.y, 0, index);
					index++;
				}
			}

			if (hasNormals)
			{
				index = 1;
				for (auto vn : vnsTemp)
				{
					os << "vn " << vn.x << " " << vn.y << " " << vn.z << std::endl;
					vns.emplace(vn.x, vn.y, vn.z, index);
					index++;
				}
			}

			std::wstring materialName(materials[attributes[0]].strName); // Using the first entry as they are all the same for our use cases
			os << "usemtl " << std::string(materialName.begin(), materialName.end()) << std::endl; // https://stackoverflow.com/questions/4804298/how-to-convert-wstring-into-string

			/// Now the faces, a face is the first 3 indexes in indexes on the faces vertex 
			for (int i = 0; i < indices.size(); i += 3)
			{
				os << "f ";
				for (int j = 0; j < 3; j++)
				{
					os << vs.find({ vertices[indices[i + j]].position.x, vertices[indices[i + j]].position.y, vertices[indices[i + j]].position.z, 0 })->index << "/";
					if (hasTexcoords)
						os << vts.find({ vertices[indices[i + j]].textureCoordinate.x, vertices[indices[i + j]].textureCoordinate.y, 0, 0 })->index;
					os << "/";
					if (hasNormals)
						os << vns.find({ vertices[indices[i + j]].normal.x, vertices[indices[i + j]].normal.y, vertices[indices[i + j]].normal.z, 0 })->index;
					os << " ";
				}
				os << std::endl;
			}
		}

**Comment by cdcseacave** [comment]
> 
> 
> I don't currently support writing to an Wavefront `obj` file since the format is so simple, only as an input. I can certainly consider this a feature request for the `uvatlas` tool as well as the DirectXMesh `meshconvert` which uses the same helper `Mesh` class.

`the format is so simple`: the problem is very simple as well, faces as input, faces+uv as output, for what do we need a complex mesh format?

plus most of us here, I dare to assume, do not care about the DirectX part, we only need the functionality promised in the title UV atlas generation; how do u (Microsoft) expect people to embrace your tools if they are so hard to use?

**Comment by walbourn** [comment]
@cdcseacave Keep in mind the ``uvatlastoolexe`` is intended as a sample for using the UVatlas library, not a 'product'. I agree the WaveFront OBJ output option is fairly simple, so I'll look at adding it to meshconvert and uvatlastool when time permits.

**Comment by WurmD** [comment]
Here is code to export from UVAtlasTool::Mesh to OBJ https://github.com/WurmD/UVAtlas/tree/UVAtlasToolMeshExportToOBJ

@walbourn , I mistakenly based it off the "#pragma omp" improvement that I already pull-requested. Won't you merge that one so we can pull-request this one and it only include changes relevant to ExportToOBJ? (without me having to rebase and recreate the changes)

**Comment by WurmD** [comment]
Here :) https://github.com/microsoft/UVAtlas/pull/47

Is this an acceptable first version for Exporting to OBJ?

**Comment by walbourn** [comment]
I'll look at integrating it in the next day or two, as well as getting the same functionality into [meshconvert](https://github.com/microsoft/DirectXMesh/wiki/meshconvert).

**Comment by walbourn** [comment]
@WurmD I realize attributes aren't that interesting for your use case, but I wanted to support them for meshconvert.exe anyhow.

See [this commit](https://github.com/microsoft/UVAtlas/commit/2bbef8687c7f2fb1cbe8bbc256a76d075ef188a9) for some cleanups and the attributes support. I'm moving this over to ``meshconvert.exe`` now.

**Comment by walbourn** [comment]
Meshconvert now supports export to WaveFront OBJ. See [this commit](https://github.com/microsoft/DirectXMesh/commit/9f0fd65c3d948f3f2d980ecf6297df2eda550b41).

Thanks again for the contribution!
