### ISSUE TITLE
Issues building static library with vcpkg

### ISSUE THREAD

**Issue by HowDoesOneMath** [microsoft/UVAtlas#149]
Hello

I'm trying to use UVAtlas for a personal project and am having difficulties getting the static library to build. I'm using VS 2019 and vcpkg set to static (cannot change to dynamic), and upon building am getting spammed with the following errors from just calling one function 'UVAtlasCreate': 

![image](https://github.com/microsoft/UVAtlas/assets/46619591/df4fd23f-2904-4363-9c9a-7298e34b7b2f)
![image](https://github.com/microsoft/UVAtlas/assets/46619591/663a0d9e-09c0-4dec-872b-f561dad2b1b6)

Is there an easy solution to this? I would prefer not to use cmake if it can be avoided.

**Comment by walbourn** [comment]
I've seen that if the library is built with VS 2022 (v143), but your project is built with VS 2019 (v142)
