### ISSUE TITLE
add information on creating correct adjacency buffers

### ISSUE THREAD

**Issue by eddiz** [Microsoft/UVAtlas#17]
The current implementation assumes implicitly a specific order of the vertex index buffer and the adjacency buffer. However I haven't found any information on this within the existing documentation. To prevent that other struggle as much as I did, I suggest to replace the current description for adjacency by one similar to that:

**adjacency**: A 32-bit index array with nFaces * 3 entries containing the adjacent triangles for each face in a mesh. Be aware that the order of the adjacent triangles is prescribed by the vertex order of the index buffer. If a triangle is defined by the indices of v1 / v2 / v3, the corresponding adjacent triangles must share the edges v1v2/ v2v3/ v3v1. If no adjacent triangle exist the index must be set to uint32_t(-1). 
Note: The adjacency buffer can be computed from mesh data using DirectXMesh

**Comment by walbourn** [comment]
Thanks. Updated the wiki on both UVAtlas and DirectXMesh to improve the description.
