### ISSUE TITLE
Nondeterministic results when run from multiple threads

### ISSUE THREAD

**Issue by Novum** [microsoft/UVAtlas#18]
In UVAtlasRepacker.cpp & meshoptimizestretch.cpp you use rand() which internally uses a global, shared seed state. This will produce nondeterministic results when calling UVAtlas from multiple threads at once, because the order of rand() calls from different threads becomes effectively random.

I recommend using C++ \<random\> with a local generator on the stack to fix this.

**Comment by walbourn** [comment]
Fixed in [this commit](https://github.com/microsoft/UVAtlas/commit/4ca2c5c6136d0afc4757ec9d9ecdb7e83856f31e)
