### ISSUE TITLE
SymmetricMatrix::GetEigen infinite loop

### ISSUE THREAD

**Issue by jdolan-zoox** [microsoft/UVAtlas#23]
I am occasionally getting infinite loops in GetEigen() on certain assets (like 2 meshes out of several thousand). Sadly I can't share the meshes that I am seeing this on, but I am using the DirectXMesh functions for generating adjacency and running Clean as well. So it should be a nice clean+manifold mesh.

It looks like sometimes the `tt` variable in GetEigen ends up as zero, results in divide-by-zero and the resulting NaN values causes the loop to never meet the condition necessary to break.

I am going to continue to dig into this on my own, but wanted to post this issue early in case its already a known issue to someone.

Repro
```
  constexpr size_t dimension_count = 4;
  constexpr size_t max_range = 2;

  constexpr float test_matrix[dimension_count * dimension_count] = {
    0x1.887c48p+2, -0x1.d3ebfap+1, -0x1.7fb8fcp+0, -0x1.f4c058p-1,
    -0x1.d3ebfcp+1, 0x1.4213f6p+2, -0x1.2b4fap-4, -0x1.4dc2e2p+0,
    -0x1.7fb8fep+0, -0x1.2b4f6p-4, 0x1.633914p-1, 0x1.c1a2d4p-1,
    -0x1.f4c06p-1, -0x1.4dc2ep+0, 0x1.c1a2dp-1, 0x1.6751a8p+0,
  };

  float eigen_value[max_range] = {};
  float eigen_vector[dimension_count * max_range] = {};

  Isochart::CSymmetricMatrix<float>::GetEigen(
    dimension_count,
    test_matrix,
    eigen_value,
    eigen_vector,
    max_range
  );
```

**Comment by walbourn** [comment]
Again, I realize it's been a long time, but this repro no longer seems to result in an infinite loop. I've done a fair amount of code cleanup for conformance and /analyze warnings, so it's possible the bug here was fixed.

**Comment by walbourn** [comment]
Note that was defintely a bug in the ``GetEigen`` code with memory usage which may have contributed to the bug here. See [this commit](https://github.com/microsoft/UVAtlas/commit/4a287a8bf3efd7cbfa705271bd672cc4155245a7).

**Comment by Anghan15** [comment]
I got the same problem. I found the floating-point control word is _DN_FLUSH(_controlfp_s(nullptr, _DN_FLUSH, _MCW_DN), which caused some dividing by zero in SymmetricMatrix::GetEigen. After clear that flag(_controlfp_s(nullptr, _DN_SAVE, _MCW_DN), the issue disappeared.

**Comment by Anghan15** [comment]
I got the same problem. I found the floating-point control word is _DN_FLUSH(_controlfp_s(nullptr, _DN_FLUSH, _MCW_DN), which caused some dividing by zero in SymmetricMatrix::GetEigen. After clearing that flag(_controlfp_s(nullptr, _DN_SAVE, _MCW_DN), the issue disappeared.
