### ISSUE TITLE
UVAtlasPartition generates NAN UVs when IMT is provided on input for certain meshes

### ISSUE THREAD

**Issue by jdolan-zoox** [microsoft/UVAtlas#24]
I have noticed that when I provide tensors as input to UVAtlasPartition I sometimes get NAN UVs out. This only happens on some meshes, and seems to happen regardless of what the tensor values are (I even tried identity [1,0,1]).

For the purposes of getting something that I can actually share and to make debugging easier I progressively clipped triangles out of a mesh until the issue stopped occurring. Attached is the last iteration  of the problem reproducing. The mesh as a result is a bit weird, and contains 3 islands of polygons. Deleting any island causes the issue to go away (I think the issue is related between the ratio between the smallest triangle and the total bounds of the mesh?).

The issue can be reproduced in UVAtlasTool in debug mode via `uvatlastool -iv TEXCOORD  bad_mesh2.obj` which actually will throw an assert due to `m_PixelWidth` ending up as nan which causes an out of bounds vector index.

[bad_mesh2.zip](https://github.com/Microsoft/UVAtlas/files/2503903/bad_mesh2.zip)

**Comment by jdolan-zoox** [comment]
The fundamental issue seems to be INFINITE_STRETCH is set to FLT_MAX, which if it ever gets used causes NANs when its inevitably multiplied/added/etc against.

**Comment by axtrend** [comment]
It happens when I use Sponza mesh and identity IMT.

**Comment by walbourn** [comment]
I know it's been quite a while since you reported this issue, but I'm not able to reproduce it with the current build of the library.
