### ISSUE TITLE
Internal error: Closed surface not correctly partitioned

### ISSUE THREAD

**Issue by Silverlan** [microsoft/UVAtlas#29]
When trying to call __DirectX::UVAtlasCreate__ with a specific mesh, it consistently fails with a `Closed surface not correctly partitioned` error. I have uploaded an example project (including the data for the mesh in question) to replicate the issue here:
[test_uvatlas.zip](https://github.com/microsoft/UVAtlas/files/3658579/test_uvatlas.zip)
The mesh is rather large, so __UVAtlasComputeIMTFromTexture__ takes a few minutes to complete.

It works fine with other, simpler meshes.

Edit:
I've tried it with another large mesh and got the same error. I have no idea what to look for, otherwise I'd try to narrow it down. Also, __DirectX::UVAtlasComputeIMTFromTexture__ can take a few hours to complete, I'm not sure if that's normal.

**Comment by walbourn** [comment]
There are a number of these warnings before the failure:

```
Try to clean the non-manifold mesh, generated by partition
```

The DirectXMesh ``Clean`` and ``Validate`` methods are very useful for conditioning the mesh before you attempt to use UVAtlas.

**Comment by chaohuang** [comment]
> There are a number of these warnings before the failure:
> 
> ```
> Try to clean the non-manifold mesh, generated by partition
> ```
> 
> The DirectXMesh `Clean` and `Validate` methods are very useful for conditioning the mesh before you attempt to use UVAtlas.
> 
> https://github.com/microsoft/DirectXMesh/wiki/DirectXMesh#mesh-cleanup-and-validation

Hi Chuck,

I checked the codes and found that the UVAtlasTool already called the DirectXMesh `Clean` and `Validate` methods before calling the `UVAtlasCreate`, but for some meshes, I still got the "closed surface not correctly partitioned" error.

Does this mean there could be some non-manifold meshes that couldn't be fixed by the DirectXMesh `Clean` and `Validate` methods, and `UVAtlasCreate` would fail on those meshes?

Thanks!

**Comment by walbourn** [comment]
Right. ``meshconvert`` only calls ``Clean`` if you use ``-c``, but ``uvatlas`` always calls it.

Do you get any warnings from ``Validate`` (which is called before ``Clean``) or just from UVAtlas?

**Comment by chaohuang** [comment]
> Right. `meshconvert` only calls `Clean` if you use `-c`, but `uvatlas` always calls it.
> 
> Do you get any warnings from `Validate` (which is called before `Clean`) or just from UVAtlas?

Yes, I got warnings from `Validate` saying "bowties found" and "vertex dups". But I thought `Clean` would take care of those issues. I also got those warnings when processing others meshes, but UVAtlasTool worked fine on those meshes.

**Comment by walbourn** [comment]
Try hacking up your local copy of uvatlas to do the ``Validate`` again after the ``Clean``. It seems like it's not fixing all the issues...

**Comment by walbourn** [comment]
OK, so the Clean worked but there's some degenerate case in your model that's tripping up UVAtlas...
