### ISSUE TITLE
CMake error: string sub-command REPLACE requires at least four arguments

### ISSUE THREAD

**Issue by jasjuang** [microsoft/UVAtlas#31]
When I run

```
git clone https://github.com/microsoft/UVAtlas/
cd UVAtlas && mkdir build && cd build
cmake ..
```

The below error shows up

```
CMake Error at CMakeLists.txt:80 (string):
  string sub-command REPLACE requires at least four arguments.


CMake Error at CMakeLists.txt:85 (string):
  string sub-command REPLACE requires at least four arguments.

-- Configuring incomplete, errors occurred!
```

I am on Ubuntu 18.04, GCC 7.

I looked into the CMakeLists at line 80, and it seems `/W3` and `/W4` are windows specific compilation flags. Should we try to guard it with an `if(MSVC)`?

**Comment by walbourn** [comment]
There are in fact four arguments:

```
string(REPLACE "/W3 " "/Wall " CMAKE_CXX_FLAGS ${CMAKE_CXX_FLAGS})
```

I use MSVC and the clang-cl "MSVC"-like front-end for clang/LLVM, but in any case it shouldn't be a problem if ``/W3`` isn't present. I suspect the issue is what generator you are using. It needs to be a C++ generator.

**Comment by jasjuang** [comment]
I just did a test and it is because `CMAKE_CXX_FLAGS` is empty so cmake probably interpret it the function as 2 or 3 arguments. See below minimal example

```
set(TESTVAR "")
string(REPLACE "/W3 " "/W4 " TESTVAR ${TESTVAR})
```

this will cause an error. Seems like the best way to deal with this is to do something like the below:

```
if(MSVC)
  # Use higher Warning Level 
  string(REPLACE "/W3 " "/W4 " CMAKE_CXX_FLAGS ${CMAKE_CXX_FLAGS})
  string(REPLACE "/W3 " "/W4 " CMAKE_CXX_FLAGS_DEBUG ${CMAKE_CXX_FLAGS_DEBUG})
  string(REPLACE "/W3 " "/W4 " CMAKE_CXX_FLAGS_RELEASE ${CMAKE_CXX_FLAGS_RELEASE})

# Not using typeid or dynamic_cast, so disable RTTI to save binary size
  string(REPLACE "/GR " "/GR- " CMAKE_CXX_FLAGS ${CMAKE_CXX_FLAGS})
  string(REPLACE "/GR " "/GR- " CMAKE_CXX_FLAGS_DEBUG ${CMAKE_CXX_FLAGS_DEBUG})
  string(REPLACE "/GR " "/GR- " CMAKE_CXX_FLAGS_RELEASE ${CMAKE_CXX_FLAGS_RELEASE})
endif()
```

What do you think?

**Comment by walbourn** [comment]
If that works, I'm happy to add that.

**Comment by walbourn** [comment]
You probably need to do the same with ``/fp:fast`` and ``/arch:SSE2``.

**Comment by jasjuang** [comment]
Yes, that allows me to get past the error. Please add it. I am still in the middle of figuring out how to make DirectXMesh work so I haven't got into the compilation stage yet hence I haven't encountered the problem by `target_compile_options` on `/fp:fast` and `/arch:SSE2`, but I think we are right, those has to be guarded with `if(MSVC)` as well.

**Comment by walbourn** [comment]
I've updated all three project:

https://github.com/microsoft/DirectXMesh/commit/9573851f22966f01b26e0f8c01949bc5fc59af34

https://github.com/microsoft/DirectXTex/commit/daf43112282001bb3bf536e53ebed07bf6532110

https://github.com/microsoft/UVAtlas/commit/01d4f94ef26aafa370aa172925a58c637f034d44
