### ISSUE TITLE
Windows Subsystem for Linux support 

### ISSUE THREAD

**Issue by jasjuang** [microsoft/UVAtlas#33]
After applying https://github.com/microsoft/UVAtlas/pull/32, https://github.com/microsoft/DirectXMesh/pull/42, and https://github.com/microsoft/DirectXTex/pull/158, I can successfully configure CMake but I ran into trouble compiling with the below error:

```
In file included from /home/jasjuang/UVAtlas/UVAtlas/geodesics/ApproximateOneToAll.cpp:10:0:
/home/jasjuang/UVAtlas/UVAtlas/pch.h:64:10: fatal error: Windows.h: No such file or directory
 #include <Windows.h>
          ^~~~~~~~~~~
compilation terminated.
```

Is UVAtlas intended for Windows only? or is there a way to configure it to make it work on Linux, more specifically Ubuntu 18.04, GCC 7?

**Comment by walbourn** [comment]
Generally speaking all my GitHub libraries assume the Windows SDK, except for [DirectXMath](https://github.com/Microsoft/DirectXMath).  UVatlas (the library, not the tool) is mostly Standard C++ at this point, but it does use:

* The ``DXGI_FORMAT`` enum from dxgiformat.h
* ``HRESULT`` and related defines/macros from winerror.h
* There's also one instance of a Win32 Mutex that could be updated to a C++11 mutex.
*  There are a few lingering uses of ``DWORD``, ``LPCSTR``, and other "Windows" types that can be removed or changed.

My use for CMake is primarily to use clang for Windows in addition to MSVC.

**Comment by walbourn** [comment]
Between [directx-headers](https://github.com/Microsoft/DirectX-Headers) and [directxmath](https://github.com/Microsoft/DirectXMath), it should be possible to build *DirectXMesh* for Linux targets.

The work would be done in the source and for CMakeLists.txt, leveraging ``find_package``.

**Comment by walbourn** [comment]
Useful for non-Windows systems: https://github.com/microsoft/DirectX-Headers/blob/main/include/wsl/winadapter.h
