### ISSUE TITLE
Reorganize header files to avoid header conflicts

### ISSUE THREAD

**Issue by jasjuang** [microsoft/UVAtlas#36]
I am in the middle of adding `export` and `install` into the CMakeLists and I noticed a problem. There's no sort of guard when including the headers. [For example](https://github.com/microsoft/UVAtlas/blob/master/UVAtlas/geodesics/ApproximateOneToAll.cpp#L12) , it includes `mathutils.h`, this could be a problem if we `install` UVAtlas along with other open-source and system libraries because it's very possible that some other libraries might also have a header called `mathutils.h` as well. Would you be open to reorganizing the folder structure so that the code will include the headers like `UVAtlas/mathutils.h`? With this folder guard, it is guaranteed to not have conflict while installing it alongside with other open-source libraries. This is a common practice done by popular open-source libraries like OpenCV, PCL, CGAL, etc.

**Comment by walbourn** [comment]
The only 'public' header is the one in side ``UVAtlas\UVAtlas\inc`` so other projects shouldn't see any other header.

**Comment by jasjuang** [comment]
That will make reorganization significantly easier. I did a search on the repo and only a few files have `#include "UVAtlas.h"` in them. Should we just reorganize `UVAtlas.h` so that the include becomes `#include "UVAtlas/UVAtlas.h"` and leave other header files alone?
