### ISSUE TITLE
Should Cal2DTriangleArea() add fabs to the return value ?

### ISSUE THREAD

**Issue by anuwat82** [microsoft/UVAtlas#4]
I am not sure about theory here.
But Cal2DTriangleArea() 's equation is 2D triangle area by coordinates formula except it doesn't have absolute operation.

Should it be fabs( ((v1.x - v0.x)*(v2.y - v0.y) ..... / 2);?

**Comment by walbourn** [comment]
The UVAtlas codebase is quite old, so it's challenging to dig into the history here.

It looks like the callers of this helper function do the ``fabs`` instead of it being done in the function itself which would probably have made more sense.
