### ISSUE TITLE
UVAtlas outputting invalid indexes with larger meshes

### ISSUE THREAD

**Issue by WurmD** [microsoft/UVAtlas#40]
https://stackoverflow.com/questions/59973896/how-to-use-uvatlas-to-process-larger-meshes-65k-uint16

Adding the following test to https://github.com/walbourn/uvatlastest UVAtlas outputs an invalid number of indexes which fails this test `(ib.size() / (sizeof(uint32_t) * 3)) != nFaces || facePart.size() != nFaces`

	bool Test11()
	{
		wchar_t szPath[MAX_PATH] = { L"C:\\Users\\wurmd\\Work\\UVAtlas3\\Tests\\data\\John40K.obj" };

		std::unique_ptr<WaveFrontReader<uint32_t>> mesh(new WaveFrontReader<uint32_t>());
		mesh->Load(szPath);

		size_t nFaces = mesh->indices.size() / 3;
		size_t nVerts = mesh->vertices.size();

		std::unique_ptr<XMFLOAT3[]> pos(new XMFLOAT3[mesh->vertices.size()]);
		for (size_t j = 0; j < mesh->vertices.size(); ++j)
			pos[j] = mesh->vertices[j].position;
		std::unique_ptr<uint32_t[]> adj(new uint32_t[mesh->indices.size()]);
		memset(adj.get(), 0xff, sizeof(uint32_t) *  mesh->indices.size());
		GenerateAdjacencyAndPointReps(mesh->indices.data(), mesh->vertices.size() / 3, pos.get(), mesh->vertices.size(), 0.f, nullptr, adj.get());

		HRESULT hr;

		std::vector<UVAtlasVertex> vb;
		std::vector<uint8_t> ib;
		std::vector<uint32_t> facePart;
		std::vector<uint32_t> remap;
		float maxStretch = 0.f;
		size_t numCharts = 0;
		hr = UVAtlasCreate(pos.get(), mesh->vertices.size(), mesh->indices.data(), DXGI_FORMAT_R32_UINT, mesh->vertices.size() / 3,
			0, 0.f, 512, 512, 1.f,
			adj.get(), nullptr, nullptr, UVAtlasCallback, UVATLAS_DEFAULT_CALLBACK_FREQUENCY,
			UVATLAS_DEFAULT, vb, ib, &facePart, &remap, &maxStretch, &numCharts);

		if (FAILED(hr))
		{
			printe("\nERROR: create atlas failed (%08X)\n%S\n", hr, szPath);
		}
		else if (vb.size() < nVerts
			|| (ib.size() / (sizeof(uint32_t) * 3)) != nFaces
			|| facePart.size() != nFaces
			|| remap.size() != vb.size()
			|| !numCharts)
		{
			std::cout << "[ERROR] (vb.size() < nVerts || (ib.size() / (sizeof(uint32_t) * 3)) != nFaces || facePart.size() != nFaces || remap.size() != vb.size() || !numCharts)" << std::endl;
			std::cout << "        (" << vb.size() << " < " << nVerts << " || " << (ib.size() / (sizeof(uint32_t) * 3)) << " != " << nFaces << " || " << facePart.size() << " != " << nFaces << " || " << remap.size() << " != " << vb.size() << " || " << !numCharts << ")" << std::endl;
			printe("\nERROR: Unexpected results from create atlas:\n%S\n\tverts %zu\n\tfaces %zu (%zu bytes)\n\tface partitions %zu\n\tremap array %zu\n\tmaxStretch %f\n\tnumCharts %zu\n",
				szPath, vb.size(), nFaces, ib.size(), facePart.size(), remap.size(), maxStretch, numCharts);
		}
		else if (!IsValidVertexRemap(reinterpret_cast<const uint32_t*>(ib.data()), nFaces, remap.data(), vb.size(), true))
		{
			printe("\nERROR: Vertex remap invalid from create atlas:\n%S\n", szPath);
		}
		else if (!IsValidFacePartition(facePart.data(), nFaces, numCharts))
		{
			printe("\nERROR: Face partition invalid from create atlas:\n%S\n", szPath);
		}
		else if (!VerifyVertices(pos.get(), nVerts, vb.data(), remap.data(), vb.size()))
		{
			printe("\nERROR: Vertex data doesn't match remap:\n%S\n", szPath);
		}
		else
		{
			std::wstring msgs;
			hr = Validate(reinterpret_cast<const uint32_t*>(ib.data()), nFaces, vb.size(), nullptr, VALIDATE_DEFAULT, &msgs);
			if (FAILED(hr))
			{
				printe("\nERROR: Invalid index buffer from create atlas (%08X):\n%S\n%S\n", hr, szPath, msgs.c_str());
			}
		}

		return true;
	}

Issue reproducible with this data: https://www.dropbox.com/s/0h9imgomldqipi4/John40K.zip?dl=0

**Comment by WurmD** [comment]
@walbourn , I'll be happy to pull request to https://github.com/walbourn/uvatlastest the new test for larger meshes when we succeed at making it run.

**Comment by walbourn** [comment]
This is similar to the test I do in ``Test08`` in process.cpp which just runs through a number of WaveFront object files. Adding your file to that test is probably the best long-term case.

Note I store the media in another git using LFS [here](https://github.com/walbourn/directxmeshmedia).

**Comment by walbourn** [comment]
That model is too large for 16-bit indices in ``Test08`` which is fine and easy to extend.

I do notice trying to process that model I get warnings:

```
UVAtlas: Try to clean the non-manifold mesh, generated by partition
```

**Comment by walbourn** [comment]
There's a problem in your test code above when computing the adjacency.

```
GenerateAdjacencyAndPointReps(mesh->indices.data(), mesh->vertices.size() / 3, pos.get(), mesh->vertices.size(), 0.f, nullptr, adj.get());
```

The number of faces is *not* the size of the vertices divided by three... It's the number of indices divided by three. It needs to be:

```
GenerateAdjacencyAndPointReps(mesh->indices.data(), mesh->indices.size() / 3, pos.get(), mesh->vertices.size(), 0.f, nullptr, adj.get());
```

-or-

```
GenerateAdjacencyAndPointReps(mesh->indices.data(), nFaces, pos.get(), nVerts, 0.f, nullptr, adj.get());
```

Your test code above isn't checking for errors coming back from ``GenerateAdjacencyAndPointReps``

**Comment by WurmD** [comment]
Good catch. I’m sorry for wasting your time on that.
I’ve corrected that, made it closer to Test08 and ran again successfully.

I see marginal difference in speed and memory for Head_Big_Ears._obj between uint16 to uint32

Head_Big_Ears._obj 
uint16 21s 72MB
uint32 24s 73MB

So I will submit a pull request to Test08 changing it to always be uint32, adding the call to the John data
And submit a pull request to the dataset with the John data

**Comment by WurmD** [comment]
You already did it. Great work then :)

**Comment by walbourn** [comment]
@WurmD: Yes, I realized I had a testing gap there. I'll add the Head_Big_ears._obj to the 32-bit test case as well.
