### ISSUE TITLE
Free 20% speed-up with simple #pragma omp parallel for

### ISSUE THREAD

**Issue by WurmD** [microsoft/UVAtlas#41]
Adding to https://github.com/microsoft/UVAtlas/blob/master/CMakeLists.txt

    # #pragma omp is used to specify Directives and Clauses. If /openmp is not specified in a compilation, the compiler ignores OpenMP clauses and directives
    add_compile_options($<$<CXX_COMPILER_ID:MSVC>:/openmp>)

And to https://github.com/microsoft/UVAtlas/blob/master/UVAtlas/isochart/meshoptimizestretch.cpp#L387

```
-    for (size_t ii=0; ii<chartList.size(); ii++)
+#pragma omp parallel for
+    for (int ii = 0; ii < chartList.size(); ii++)
     {
         float fEii = chartList[ii]->m_fParamStretchL2;
         float faii = chartList[ii]->m_fChart2DArea;
-        bAllChartSatisfiedStretch =
+        bAllChartSatisfiedStretch =
             (bAllChartSatisfiedStretch && (fEii == faii));

-        fSumSqrtEiiaii += IsochartSqrtf(fEii * faii);
+        auto temp = IsochartSqrtf(fEii * faii); // For max speed-up
+#pragma atomic
+        fSumSqrtEiiaii += temp;
```

Gives a 20% speed up in a machine with 12 cores, for "free", since if the compiler doesn't accept the /openmp flag it should ignore the changes suggested here and proceed as normal single-threaded

I tried pull-requesting, but no permissions

**Comment by walbourn** [comment]
You can create a fork of the project and then a PR from your fork to the master.

**Comment by WurmD** [comment]
https://github.com/microsoft/UVAtlas/pull/42 done
