### ISSUE TITLE
[Question] isochartpartition parallelization

### ISSUE THREAD

**Issue by WurmD** [microsoft/UVAtlas#43]
I'm working to further parallelize UVAtlas.
Reading the paper Zhou et al, "Iso-charts: Stretch-driven Mesh Parameterization using Spectral Analysis", Eurographics Symposium on Geometry Processing (2004), and inspecting the code.

The first step of the isochart algorithm is "1. Compute the surface spectral analysis, providing an initial parameterization"

80% of the current processing time is spent on this step, namely in `CIsochartEngine::ParameterizeChartsInHeap(bCountParition, MaxChartNumber));`
This function works on a chart heap (implemented based on a vector), going one by one doing the parameterization and if the results for that chart aren't good enough, splits it and adds the two child charts to the end of the heap

This seems to be a good candidate for parallellization.

**Question: Are you aware of something in the algorithm that outright prevents this step from being parallelizable? (chart parameterization *needs* to be computed serially as they depend on each other?)**

**Comment by walbourn** [comment]
Fixed in [this pull request](https://github.com/microsoft/UVAtlas/pull/48)
