### ISSUE TITLE
UVAtlas not using all available texture map space

### ISSUE THREAD

**Issue by WurmD** [microsoft/UVAtlas#45]
For this OBJ https://www.dropbox.com/s/jydhp5qzechaxli/manual.obj?raw=1 (with [mlt](https://www.dropbox.com/s/v680ra6j41wnuul/manual.mtl?raw=1) and [image](https://www.dropbox.com/s/0ez8u23p3z5zvhb/imageBlendedAfter100.png?raw=1) ) 

	v   0.0  0.0  0.0
	vt  0.0  0.0
	vn -0.7  0.0  0.7

	v   0.0 10.0  0.0
	vt  0.0  1.0
	vn -0.7  0.0  0.7

	v  10.0  0.0 10.0
	vt  0.585  0.0
	vn  0.0  0.0  1.0 

	v  10.0 10.0 10.0
	vt  0.585  1.0
	vn  0.0  0.0  1.0 

	v  20.0  0.0  0.0
	vt  1.0  0.0
	vn  0.7  0.0  0.7

	v  20.0 10.0  0.0
	vt  1.0  1.0
	vn  0.7  0.0  0.7

	usemtl 2imagesconcatenated
	f 1/1/1 3/3/3 2/2/2 
	f 2/2/2 3/3/3 4/4/4
	f 3/3/3 5/5/5 4/4/4 
	f 4/4/4 5/5/5 6/6/6

That exemplifies a complete usage of the texture map thusly
![manual](https://user-images.githubusercontent.com/5755747/74038243-c0295b00-49b7-11ea-8d01-4e9a31510356.png)

UVAtlas outputs 

	v 0 0 0
	v 0 10 0
	v 10 0 10
	v 10 10 10
	v 20 0 0
	v 20 10 0
	vt 0.000726879 0.999851
	vt 0.000726938 0.5
	vt 0.000727028 0.000148656
	vt 0.354175 0.999851
	vt 0.354175 0.5
	vt 0.354175 0.000148698
	vn -0.7 0 0.7
	vn 0 0 1
	vn 0.7 0 0.7
	usemtl 2imagesconcatenated
	f 1/6/1 3/5/2 2/3/1 
	f 2/3/1 3/5/2 4/2/2 
	f 3/5/2 5/4/3 4/2/2 
	f 4/2/2 5/4/3 6/1/3 

![manual obj_new](https://user-images.githubusercontent.com/5755747/74038898-d388f600-49b8-11ea-8030-f9e5e298e4be.png)

**which only uses the left third of the texture space**

**Comment by WurmD** [comment]
Is this due to stretch minimization?

**Comment by walbourn** [comment]
I believe it is due to stretch minimization. Did you try other settings?

**Comment by PerspectivesLab** [comment]
@WurmD  could you share us the paramaters you used to fullfill the map ? thx
