### ISSUE TITLE
Gutter usage

### ISSUE THREAD

**Issue by cdcseacave** [microsoft/UVAtlas#46]
Great library, it works as I was hopping, thank you.
I am not sure if it's an issue or simply I do not know how to use it: I expect by setting the `gutter` parameter for ex to 2, that the atlas packing reserves an extra border of 2 pixels thickness around each chart. However when I draw the texture using the computed `uv` coordinates the charts are using the entire space (touche the limits of the image) without letting any space for me to fill in with the border pixels.
I feel I am missing something fundamental here, pls help.

**Comment by walbourn** [comment]
See the [wiki](https://github.com/Microsoft/UVAtlas/wiki/UVAtlasCreate):

> gutter: The minimum distance, in texels between two charts on the atlas. This gets scaled by the width, so if gutter is 2.5, and it is used on a 512x512 texture, then the minimum distance will be 2.5 / 512 in u-v space.

**Comment by cdcseacave** [comment]
I saw the wiki, but I wrote here as that is not enough. So now it is clear this is an issue and not a misunderstanding. How is anybody able to add any extra pixels around the charts (for bilinear interpolation, etc) if they extend to the image limits??? The gutter should be between charts but ALSO between charts and the image limits! the only option now is to give you a smaller image resolution, and after your lib to shift all texture coordinates!!!

**Comment by cdcseacave** [comment]
And after looking into the code trying to fix it myself, it turns out even the documentation is wrong, 2 mistakes:
- it can not be a float value like 2.5, as the first thing that happens inside the lib is to convert it to int
- second the empty space seems to be 2*gutter (as it should be normal actually) and not just gutter as in the docs
Do you know this code in fact?
