### ISSUE TITLE
crashes

### ISSUE THREAD

**Issue by cdcseacave** [microsoft/UVAtlas#51]
trying to process this mesh results in a crash
this particular mesh is not looking nice, I submit this one as it is the smallest one I was able to reproduce the problem; there are many more crashing but are much larger; all of them are manifold, and free of any problems as much as I can tell
[scene_mesh_texture.zip](https://github.com/microsoft/UVAtlas/files/4346046/scene_mesh_texture.zip)

any idea what the problem is?

**Comment by walbourn** [comment]
Are you using the x64 native version of the library/tool or 32-bit?

**Comment by cdcseacave** [comment]
x64

**Comment by walbourn** [comment]
I was not able to reproduce any failure here. Did you have any specific command-line arguments beyond the file name?

**Comment by walbourn** [comment]
I tried running it in Release and I eventually got it to fail with:

```
Exception thrown at 0x00007FFE8A474B89 in uvatlastool.exe: Microsoft C++ exception: std::bad_alloc at memory location 0x00000061F0AFF030.
```

Not sure how it ran out of memory, but it did.
