### ISSUE TITLE
Build with Unity iOS platform

### ISSUE THREAD

**Issue by orangeagain** [microsoft/UVAtlas#57]
I need to compile this library with unity for ios.
In my mind, there are two way to achive it:

### 1.take souce code to unity, then build together with ic2cpp.
[C++source code plugins for IL2CPP](https://github.com/microsoft/UVAtlas/issues/url)

### 2.build static lib for unity.(use xcode build static lib)
Two ways not available now. Do you have any plan to support this?

**Comment by walbourn** [comment]
I don't have any iOS or Mac hardware or development environment to work with, but you can take a look at the CMakeLists.txt to see if you can add the required support. I did recently add support for non-Win32 platforms to support Windows Subsystem for Linux, so that should help.

**Comment by orangeagain** [comment]
actually ios build test don't need apple device.
if windows il2cpp build pass, ios will pass too.
