### ISSUE TITLE
UVAtlas is quadratic in the number of boundaries

### ISSUE THREAD

**Issue by bitonic** [microsoft/UVAtlas#58]
In the `PrepareProcessing` step, this loop https://github.com/microsoft/UVAtlas/blob/4607a948f02959feeb415230dddd7c4be3b1ced2/UVAtlas/isochart/isochartengine.cpp#L1264 will essentially run once per boundary. A bit below in the stack, this function https://github.com/microsoft/UVAtlas/blob/4607a948f02959feeb415230dddd7c4be3b1ced2/UVAtlas/isochart/isochartmesh.cpp#L2792 will run, calculating the minimum path for each boundaries. Moreover, `CalMinPathToOtherBoundary` loops through all the vertices multiple times.

This makes the complexity of the prepare step `O(number_of_boundaries * number_of_boundaries * number_of_vertices)`

I have attached a mesh made out of ~150000 vertices and ~5000 boundaries (mostly composed of 0-area holes, but I don't think that matters). In this case the runtime of `PrepareProcessing` is unbearably slow (I let it run for 4hrs and it did not terminate). The flame graph looks something like this:

![Screenshot from 2021-03-01 07-41-33](https://user-images.githubusercontent.com/556090/109461004-d7733480-7a61-11eb-9bf3-51d47f326b94.png)

I might give a shot at fixing this myself, but I wanted to report this behavior for other users first.

[mesh-clean.zip](https://github.com/microsoft/UVAtlas/files/6059600/mesh-clean.zip)

**Comment by bitonic** [comment]
Possible more precise implementation idea:

* Store the information about boundaries (`allBoundaryList`, `boundaryRecord`, distance between boundary extrema) per-mesh, rather than globally;
* When cutting a chart by joining two boundary extrema, invalidate only the information for the boundaries in the same mesh.

This would fix the pathological behavior in my case, since it's not the case that a single connected component has 5k boundaries. I suspect this will be the case for most meshes, although I'm not sure. It would definitely be an improvement.

**Comment by bitonic** [comment]
Actually, even more generally: we can store the boundary information per-chart, and then invalidate information within the same chart.

**Comment by bitonic** [comment]
I realized I could also just run `UVAtlasPartition` manually on the separate meshes, then merge the data, then call `UVAtlasPack`, and that should probably resolve my problem.

**Comment by walbourn** [comment]
If you have a pull request with this optimization, I'd be happy to take a look at it.
