### ISSUE TITLE
Portable version of UVAtlas ?

### ISSUE THREAD

**Issue by vlj** [Microsoft/UVAtlas#6]
UVAtlas lib currently relies on Windows.h and DirectXMaths.h which are not available on non Windows platform. 
Would a Pull Request replacing all call to Windows specific headers with Platform agnostic lib (glm, Eigen) and a cmake build system be accepted in this repo ?

**Comment by walbourn** [comment]
Actually, the latest version of DirectXMath is available under an open-source license on [GitHub](https://github.com/Microsoft/DirectXMath). It's use of ``windows.h`` is entirely optional. If you have problems getting the intriniscs code to compile for your platform, you can use ``#define _XM_NO_INTRINSICS_`` before it to force the C codepaths.

**Comment by vlj** [comment]
thanks, I didn't know DirectXMath was available on Github.
