### ISSUE TITLE
How to build arm64 architecture by cmake on linux?

### ISSUE THREAD

**Issue by orangeagain** [microsoft/UVAtlas#61]
When my build finished,cmake generated libUVAtlas.a file. Is this file can use for all platform?
If it isn't,and How to generate target file for arm64?

**Comment by walbourn** [comment]
I used a combination of the [vcpkg C++ Manager](https://github.com/microsoft/vcpkg), and Windows Subsystem for Linux on both x64 and arm64 devices to validate the libraries build.

This is a C++ native code library, so you have to build the code specifically for each target platform: x86, x64, arm, arm64. For arm64, you need to be using GCC for arm64 (called [AArch64](https://gcc.gnu.org/onlinedocs/gcc/AArch64-Options.html))
