### ISSUE TITLE
Exposed C Interface

### ISSUE THREAD

**Issue by orangeagain** [microsoft/UVAtlas#63]
Exposed C Interface,please.
So we can call this library as real library from other language(example C#).

**Comment by walbourn** [comment]
The ABI for this library is C++, as I make use of the ``std::vector`` STL container in the API for handling the data return.

The recommendation here is that you create your own C ABI DLL interface wrapper, then implement it using the C++ ABI. You would have to make some decision about how to communicate back the buffer needs, who owns the memory, etc. which are all up to you as the implementer of the DLL wrapper.
