### ISSUE TITLE
loading an obj doesnt work

### ISSUE THREAD

**Issue by PerspectivesLab** [microsoft/UVAtlas#69]
hi, im compiling the code or using the binary tool you provide:  loading a obj file from assets: directxmeshmedia
impossible to load any obj file... indices and vertices are always 0.... 
i am sure im a loading the obj, in the debug ptr: wfReader is valid
any clue about what is going on ? thx

```
    WaveFrontReader<uint32_t> wfReader;
    HRESULT hr = wfReader.Load(szFilename, ccw);
    if (FAILED(hr))
        return hr;

    inMesh.reset(new (std::nothrow) Mesh);
    if (!inMesh)
        return E_OUTOFMEMORY;

    if (wfReader.indices.empty() || wfReader.vertices.empty()) <== always 0, 
        return E_FAIL;
```

**Comment by walbourn** [comment]
What filename did you use?

**Comment by PerspectivesLab** [comment]
by example: dodecahedron._obj
so 
`uvatlastool.exe dodecahedron._obj`
either sources or latest build,
thx

**Comment by walbourn** [comment]
That works for me.

Can you attach your copy of ``dodecahedron._obj`` that is failing?

**Comment by PerspectivesLab** [comment]
@walbourn  here is the file, i desactivated my antivirus, cmd console in admin mode, really wierd
it could be an issue with my computer, ill try with another and let you know, thanks for your time

```
# OBJ file created by ply_to_obj.c
#
g Object001

v  -0.57735  -0.57735  0.57735
v  0.934172  0.356822  0
v  0.934172  -0.356822  0
v  -0.934172  0.356822  0
v  -0.934172  -0.356822  0
v  0  0.934172  0.356822
v  0  0.934172  -0.356822
v  0.356822  0  -0.934172
v  -0.356822  0  -0.934172
v  0  -0.934172  -0.356822
v  0  -0.934172  0.356822
v  0.356822  0  0.934172
v  -0.356822  0  0.934172
v  0.57735  0.57735  -0.57735
v  0.57735  0.57735  0.57735
v  -0.57735  0.57735  -0.57735
v  -0.57735  0.57735  0.57735
v  0.57735  -0.57735  -0.57735
v  0.57735  -0.57735  0.57735
v  -0.57735  -0.57735  -0.57735

f  19  3  2
f  12  19  2
f  15  12  2
f  8  14  2
f  18  8  2
f  3  18  2
f  20  5  4
f  9  20  4
f  16  9  4
f  13  17  4
f  1  13  4
f  5  1  4
f  7  16  4
f  6  7  4
f  17  6  4
f  6  15  2
f  7  6  2
f  14  7  2
f  10  18  3
f  11  10  3
f  19  11  3
f  11  1  5
f  10  11  5
f  20  10  5
f  20  9  8
f  10  20  8
f  18  10  8
f  9  16  7
f  8  9  7
f  14  8  7
f  12  15  6
f  13  12  6
f  17  13  6
f  13  1  11
f  12  13  11
f  19  12  11

```

**Comment by walbourn** [comment]
I'm wondering if it's an issue with newlines in your enlistment. Please attach the file so I can look at in binary.

**Comment by PerspectivesLab** [comment]
[dodecahedron.zip](https://github.com/microsoft/UVAtlas/files/7229506/dodecahedron.zip)
here it is

**Comment by walbourn** [comment]
Weird. It's identical to mine.

**Comment by PerspectivesLab** [comment]
yeah, ill try to investigate more and let you know,

**Comment by walbourn** [comment]
I believe this is related to a locale issue. I've fixed it in [this commit](https://github.com/microsoft/DirectXMesh/commit/66451d179b8c14506fa05fde33548967c79b82f1), but will need to update UVAtlas with an updated NuGet soon.

**Comment by walbourn** [comment]
This issue should be fixed in the November 2021 release

https://github.com/microsoft/UVAtlas/releases/tag/nov2021
