### ISSUE TITLE
Is there a way to keep existing UVs?

### ISSUE THREAD

**Issue by braddabug** [microsoft/UVAtlas#7]
I have a model with existing UVs for texturing, but I want to calculate new UVs for lightmapping. That means I need to be able to keep the existing UVs. Is there a way to do that? It'd be nice if there were a way to end up with a model with 2 UV channels, one with the existing UVs and one with the new atlas UV coords.

**Comment by walbourn** [comment]
Are you asking for this to be exposed with the [uvatlas tool](https://github.com/Microsoft/UVAtlas/wiki/UVAtlasTool) sample?

**Comment by braddabug** [comment]
Yeah, I was asking about the uvatlas tool. I guess in the meantime I'll investigate modifying the tool myself.

**Comment by walbourn** [comment]
Note that only ``SDKMESH`` can support multiple UV sets.  ``CMO`` and WaveFront OBJ only support single UV sets.
