### ISSUE TITLE
Why the number of vertices is increased?

### ISSUE THREAD

**Issue by Armen-J** [microsoft/UVAtlas#73]
When running the ".\uvatlastool.exe -wf average.obj", the number of vertices in the resulting file is increased. How can I keep it the exact same?

**Comment by walbourn** [comment]
If you are getting additional vertices it's coming from the ``Clean`` needed to break bow-ties. If the model contains non-convex surfaces, it can get stuck in an infinite loop.

**Comment by Armen-J** [comment]
But another thing is that in the new .obj file even the coordinates of previous vertices are changed! And there is no way to figure out the mapping!
Let's say in the original file there are 1000 vertices and in the file created by uvatlastool there are 1050, is there any way to map between the original 1000 and their corresponding vertices in the new file?

**Comment by walbourn** [comment]
That information is definetly prsent

**Comment by Armen-J** [comment]
That would be great!
Could you direct me to the file and function that provides the remapping?

**Comment by walbourn** [comment]
Added in this commit https://github.com/microsoft/UVAtlas/commit/4a16541b500b136694d96296ae0b01500eb0ac3f a new ``-m`` option that writes out a text file of the form:

```
newIndex,oldIndex
```

That tells you for each index in the output mesh, what vertex in the original mesh did it come from.
