### ISSUE TITLE
How to make consistent UV atlases?

### ISSUE THREAD

**Issue by chaohuang** [microsoft/UVAtlas#74]
I have 2 meshes that are very similar; they only differ in the positions and connectivity of a few vertices. However, the generated UV atlases from those 2 meshes are totally different: not only is the packing different, the partition is also very different. For example, the head is in a single chart from the partition of one mesh, but in the partition of the other mesh, the face is divided into 2 charts.

I wonder if there is a way to make consistent atlases from similar meshes. In other words, given 2 similar meshes, the partition should be roughly the same (cut from roughly the same locations), and the packing should put similar charts from the 2 meshes at roughly the same location in the UV space (e.g. the charts containing head are both placed at the top-left corners of the UV space of the 2 meshes).

Thanks!

**Comment by walbourn** [comment]
This may be somewhat related to https://github.com/microsoft/UVAtlas/issues/84
