### ISSUE TITLE
Is there a way to make charts aligned?

### ISSUE THREAD

**Issue by braddabug** [Microsoft/UVAtlas#8]
When I generate a UV atlas for a model it seems the charts are oriented randomly. It'd help if each chart was rotated to minimize its bounding box. That way the edges of square charts would end up aligned to texels, which would help with things like lightmapping.

Is there a way to do this? If not, can there be?

**Comment by walbourn** [comment]
The UVAtlas open source library is basically just the functionality that was in the deprecated ``D3DX9`` library which did not included the alignment. That said, for light-mapping the functionality in the [gutter helper](https://github.com/Microsoft/UVAtlas/issues/1) might be useful.
