### ISSUE TITLE
How to compile UVAtlasTool under linux?

### ISSUE THREAD

**Issue by niyunsheng** [microsoft/UVAtlas#81]
In the line 42 of `UVAtlas-main/UVAtlasTool/UVAtlas.cpp`:
```cpp
#include <conio.h>
```
This head file is only for windows platform.

I want to use UVAtlasTool under linux platform, can you give me some advice?

**Comment by walbourn** [comment]
The command-line tool would need porting to Linux which is out of scope for my needs, but you are welcome to do so. ``uvatlastool`` is effectively a 'sample' for the library.

**Comment by gyxiaochina** [comment]
Happened to find an easier way to run uvatlastool on linux. You can use wine [(wine)](https://wiki.winehq.org/Wine_User%27s_Guide#How_to_run_Windows_programs_from_the_command_line) to run the uvatlastool command line. Just build the .exe from the VS solution on windows, then copy the .exe to linux computer. One trick here is that you need to build the .exe in release version, not debug version. Hope this helps.

**Comment by mgrewe** [comment]
Was anybody successful in native Linux compilation? Maybe worth giving https://github.com/thradams/conio a try.
