### ISSUE TITLE
uvatlastool generates additional vertices with already-unique faces

### ISSUE THREAD

**Issue by Raildex** [microsoft/UVAtlas#88]
I am integrating uvatlastool.exe into my toolchain.
For that I generate a obj file and pass it into uvatlastool.exe
My mesh has unique positions,uvs and normals per face (i.e. the attributes are not shared)

However, when I read the resulting obj file, i noticed that the tool generated additional vertices by merging triangles into quads together (i.e. 2 triangles form a rectangle)
I would like to have an option to forbid the generation of this "merging".

I use the tool with `-wf -q QUALITY -nologo -ga`
[lightmap.zip](https://github.com/microsoft/UVAtlas/files/10201963/lightmap.zip)

**Comment by walbourn** [comment]
Did you determine the tool was correct or is there still a bug here?

**Comment by Raildex** [comment]
The tool was correct :)
