### ISSUE TITLE
How can i re-adjust the UV mapping?

### ISSUE THREAD

**Issue by SweetBullet** [Microsoft/UVAtlas#9]
I have a model with a texture, then I remove some useless triangles of the model so that some area of the texture picture can be removed. And i want to compress the texture picture, I have to re-adjust the UV mapping of the model accordingly.  How do i use the UVAtlas?maybe i should use the function "UVAtlasCreate"?    (An urgent problem TT)

**Comment by walbourn** [comment]
The UVAtlasTool is basically a sample demonstrating how to use the UVAtlas library. Check out [UVAtlas.cpp](https://github.com/Microsoft/UVAtlas/blob/master/UVAtlasTool/UVAtlas.cpp) if you need any clarifications not covered in the [wiki](https://github.com/Microsoft/UVAtlas/wiki/uvAtlas).
