### ISSUE TITLE
[problem] UV triangles will overlap/conflict

### ISSUE THREAD

**Issue by niyunsheng** [microsoft/UVAtlas#94]
After UV unfold using UVAtlasTool, I found that UV triangles will overlap/conflict sometimes. 

As shown in the figure below.  

![uv-triangle-overlap](https://user-images.githubusercontent.com/62385270/213100229-912624df-4990-420f-8b7e-fd5055159657.png)

This situation does not happen every time. How to avoid this?

**Comment by walbourn** [comment]
Are you 'cleaning' the mesh before processing to eliminate non-manifold triangles?

**Comment by niyunsheng** [comment]
Yes. This conflict occurs after I "cleaning" the non-maniflod triangles using Meshlab.
And there was no such problem before the "cleaning".
